### ISSUE TITLE
Doesn't preserve UTF-8

### ISSUE THREAD

**Issue by zessx** [octopress/autoprefixer#3]
I've got a few Sass files with UTF-8 characters (like § or ◄). Jekyll works well and is able to preserve the encoding (thanks to `@charset "utf-8";`).

Anyway, when I add this Autoprefixer version, it stops to keep the encoding:

    gems:
      - octopress-autoprefixer 

I can easily reproduce the issue, adding/removing autoprefixer, without changing anything else.

And if I look into the generated file `main.css`, I've got these character at the very beginning:

    ´╗┐html,body(...)

**Comment by imathis** [comment]
Thanks for the report. I'll try to get this fixed right away. Should I be able to reproduce this bug with a Sass file containing this?

```
@charset "utf-8";
h2 { before: "§"; }
```

**Comment by imathis** [comment]
I just added a test with this test-case and it seems to pass just fine. Is there something I'm missing?

**Comment by zessx** [comment]
I tried a few things to find the origin, and it seems it happens only when using the sass compressed output:

    gems:
      - octopress-autoprefixer 
    sass:
      style: compressed

**Comment by imathis** [comment]
Hmm. My testing framework uses `jekyll build` not `serve` so I don't think that's the issue.

**Comment by imathis** [comment]
Would you mind creating a simple test site with only the Sass file? You could run `jekyll new test-utf8` and then add autoprefixer to the gems and the Sass file. Then run jekyll build` to see if it handles the UTF-8 conversion okay.

**Comment by zessx** [comment]
Here's what I've done:

    jekyll new test-utf8
    cd test-utf8/_sass
    printf '' > _syntax-highlighting.scss
    printf '' > _layout.scss
    printf '@charset "utf-8";\n\n::selection { color: red; }\nh2 { &:before { content: "§" } }' > _base.scss
    cd ..
    printf '\ngems:\n  - octopress-autoprefixer' >> _config.yml
    sed -i 's/baseurl: ""/baseurl: "\/test-utf8\/"/' _config.yml
    jekyll build

And the result:

    @charset "UTF-8";
    ::-moz-selection {
      color: red; }
    ::selection {
      color: red; }
    
    h2:before {
      content: "┬º"; }

**Comment by imathis** [comment]
Thanks for the easily repeatable test case! I just ran the exact same thing on my system and my resulting CSS file looks like this:

```css
@charset "UTF-8";
::-moz-selection {
  color: red; }
::selection {
  color: red; }

h2:before {
  content: "§"; }
```

I'm running OS X 10.10.3 and I don't have any UTF-8 encoding stuff in my bash profile. Do you think this may be something to do with your OS setup?

**Comment by zessx** [comment]
I think it could, I'm running Windows 7 x64.  
It's not the first time I'm facing encoding issues with Ruby stuff, but usually it's OSX which gives me a headache.

I'll investigate.

**Comment by zessx** [comment]
As a side note (it's probably related), I sometimes get this error when I build a Jekyll blog:

    jekyll 2.5.3 | Error:  "\x9D" to UTF-8 in conversion from Windows-1252 to UTF-8

This blocks the build, and comes from octopress-autoprefixer (see the following trace):

	$ jekyll serve --trace
	Configuration file: C:/wamp/www/blognew/_config.yml
	            Source: C:/wamp/www/blognew
	       Destination: C:/wamp/www/blognew/_site
	      Generating...
	C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib/execjs/encoding.rb:22:in `encode': "\x9D" to UTF-8 in conversion from Windows-1252 to UTF-8 (Encoding::UndefinedConversionError)
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib/execjs/encoding.rb:22:in `encode'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:8:in `initialize'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib/execjs/runtime.rb:44:in `new'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib/execjs/runtime.rb:44:in `compile'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib/execjs/module.rb:27:in `compile'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/autoprefixer-rails-2.2.0.20140804/lib/autoprefixer-rails/processor.rb:31:in `processor'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/autoprefixer-rails-2.2.0.20140804/lib/autoprefixer-rails/processor.rb:20:in `process'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/autoprefixer-rails-2.2.0.20140804/lib/autoprefixer-rails.rb:10:in `process'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:37:in `block in prefix'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:36:in `open'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:36:in `prefix'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:30:in `block in process'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:29:in `each'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:29:in `process'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:18:in `post_write'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:223:in `block in write'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `each'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `write'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:53:in `process'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	        from C:/Ruby200-x64/bin/jekyll:23:in `load'
	        from C:/Ruby200-x64/bin/jekyll:23:in `<main>'

It could helps you to find the origin of this issue, and helps me to find how to set my environment to avoid this kind of disagreement.

**Comment by imathis** [comment]
Have you looked at this? http://jekyllrb.com/docs/windows/

**Comment by zessx** [comment]
It seems to works!

Still doesn't work with Cygwin, but it does with native Windows console. So I need to specify the console code page to 65001. I found [this](https://github.com/imathis/octopress/blob/master/Rakefile#L32) in octopress source, which confirm my case.
